### ISSUE TITLE
TypeError: i.entries is not a function - needs a polyfill

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2268]
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/4311/?referrer=github_plugin

```
TypeError: i.entries is not a function
  at submitEnabler (./static/js/publisher/submitEnabler.js:26:30)
  at None (/account/details:306:5)
  at d (/static/js/modules/raven.min.js:2:4670)
  at [3]</</f.prototype.context (/static/js/modules/raven.min.js:2:4461)
  at None (/account/details:305:3)
```

**Comment by Lukewh** [comment]
This only seems to be an issue with IE. IE is in maintenance mode and has been replaced by Edge. Closing this as won't fix.
