### ISSUE TITLE
Can't find a SQUASHFS superblock

### ISSUE THREAD

**Issue by JacksiroKe** [canonical-web-and-design/snapcraft.io#2590]
### Expected behaviour
am doing this for the first time and hence don't know what to expect

### Steps to reproduce the problem
https://github.com/JacksiroKe/BasicQtApp/blob/master/snap/snapcraft.yaml
`snapcraft push --release=stable snap/snapcraft.yaml`

error:
```
Pushing snapcraft.yaml
After pushing, an attempt will be made to release to 'stable'
Can't find a SQUASHFS superblock on /home/future/BasicQtApp/snap/snapcraft.yaml
Sorry, an error occurred in Snapcraft:
Traceback (most recent call last):
  File "/usr/bin/snapcraft", line 11, in <module>
    load_entry_point('snapcraft==2.43.1+18.4', 'console_scripts', 'snapcraft')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/snapcraft/cli/store.py", line 161, in push
    snapcraft.push(snap_file, channel_list)
  File "/usr/lib/python3/dist-packages/snapcraft/_store.py", line 535, in push
    snap_yaml = _get_data_from_snap_file(snap_filename)
  File "/usr/lib/python3/dist-packages/snapcraft/_store.py", line 60, in _get_data_from_snap_file
    os.path.join("meta", "snap.yaml"),
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/unsquashfs', '-d', '/tmp/tmpas3zip4v/squashfs-root', '/home/future/BasicQtApp/snap/snapcraft.yaml', '-e', 'meta/snap.yaml']' returned non-zero exit status 1.
We would appreciate it if you created a bug report at
https://launchpad.net/snapcraft/+filebug with the above text included.

```
I don't know if there is something missing in my dependancies or something I can't get my head around but am new to snapcraft and am having a hard time trying to get to push to snapcraft

**Comment by Lukewh** [comment]
Hey, this is the issue tracker for snapcraft.io the website. As the error suggests, create a bug report at https://launchpad.net/snapcraft/+filebug with the error text above :+1:
