### ISSUE TITLE
Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/snapcraft.io#2783]
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/10016/?referrer=github_plugin

```
Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
  at catch (./static/js/public/snap-details/blog-posts.js:79:15)
  at promise callback*T (./static/js/public/snap-details/blog-posts.js:78:8)
  at fetch (/static/js/dist/public.js.map:27:13)
  at snapDetailsPosts (./static/js/public/snap-details/blog-posts.js:106:13)
  at None (/datagrip:1443:28)
...
(4 additional frame(s) were not displayed)
```

**Comment by tbille** [comment]
This is not happening anymore.
