### ISSUE TITLE
TypeError: e.forEach is not a function

### ISSUE THREAD

**Issue by Lukewh** [canonical-web-and-design/snapcraft.io#2822]
https://sentry.is.canonical.com/canonical/snapcraft-io/issues/10157/?referrer=github_plugin

```
TypeError: e.forEach is not a function
  at getInitialQueueTime (./static/js/publisher/builds/index.js:50:12)
  at new wo (./static/js/publisher/builds/index.js:30:38)
  at Module.xo (./static/js/publisher/builds/index.js:332:12)
  at f.<anonymous> (/vault/builds/972992:1842:29)
  at f.d (/static/js/modules/raven.min.js:2:4689)
...
(14 additional frame(s) were not displayed)
```

**Comment by anthonydillon** [comment]
Thank god, thanks @Lukewh :clap:
