### ISSUE TITLE
ARM64 builds are failing

### ISSUE THREAD

**Issue by Snawoot** [canonical-web-and-design/snapcraft.io#3432]
### Expected behaviour

Build succeeds

### Steps to reproduce the problem

Run ARM64 snap build with snapcraft.io. Get git repo cloning error:

```
Cloning into 'dumbproxy'...
fatal: unable to access 'https://github.com/Snawoot/dumbproxy/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 256, in run
    self.repo()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 175, in repo
    self.vcs_fetch(self.args.name, cwd="/build", env=env)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/vcs.py", line 94, in vcs_fetch
    self.backend.run(cmd, cwd=cwd, env=full_env)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 537, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-bionic-arm64', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build && linux64 git clone https://github.com/Snawoot/dumbproxy dumbproxy']' returned non-zero exit status 128.
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=bionic --arch=arm64 SNAPBUILD-1312232
Scanning for processes to kill in build SNAPBUILD-1312232
```

### Specs

- _URL:_ https://launchpad.net/~build.snapcraft.io/+snap/a1e6c864c8503f9f619197b12a3ffee0/+build/1312232
- _Operating system:_ Linux
- _Browser:_ Firefox 85.0.1

**Comment by Snawoot** [comment]
Issue had resolved itself after few consistently failing attempts.
