### ISSUE TITLE
Excessive/Too frequent calls to sys.exit(0) on snapcraft.io

### ISSUE THREAD

**Issue by kot0dama** [canonical-web-and-design/snapcraft.io#3785]
We've had unready pods on snapcraft.io production yesterday (between ~13:15 UTC and ~14:15 UTC). It seems there's been very quick loop-restarts of the app (which also triggered a Sentry rate limit error).

```
2021-11-29 13:58:08.059Z WARNING gunicorn.error "Worker graceful timeout (pid:7785)" service=snapcraft.io
2021-11-29 13:58:10.063Z INFO gunicorn.error "Worker exiting (pid: 7785)" service=snapcraft.io
2021-11-29 13:58:13.494Z WARNING gunicorn.error "Worker graceful timeout (pid:7661)" service=snapcraft.io
2021-11-29 13:58:15.498Z INFO gunicorn.error "Worker exiting (pid: 7661)" service=snapcraft.io
2021-11-29 13:58:19.046Z INFO gunicorn.error "Autorestarting worker after current request." service=snapcraft.io
```

Pod logs are full of these, happening at a very fast pace (every millisecond or so):
```
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 590, in spawn_worker
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/talisker/gunicorn.py", line 136, in gunicorn_worker_exit
    raise talisker.wsgi.RequestTimeout(
talisker.wsgi.RequestTimeout: finish processing ongoing requests on worker exit (pid: 7685)
```

On just one pod, in a about one hour time frame:
```
$ kubectl logs -n production snapcraft-io-b4576d88f-6995g |grep 'SystemExit: 0' | wc -l
19984
```

These were mostly happening after `GET /slack?` requests but not only, so maybe that's just the most accessed URL actually ?

Also, not sure these were related but just before they happened, we also got:
```
2021-11-29 13:19:00.338Z ERROR gunicorn.error "Error handling request" service=snapcraft.io
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/gunicorn/workers/base_async.py", line 113, in handle_request
    resp.write_file(respiter)
  File "/root/.local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 385, in write_file
    if not self.sendfile(respiter):
  File "/root/.local/lib/python3.8/site-packages/gunicorn/http/wsgi.py", line 375, in sendfile
    self.sock.sendfile(respiter.filelike, count=nbytes)
  File "/root/.local/lib/python3.8/site-packages/gevent/_socket3.py", line 490, in sendfile
    return self._sendfile_use_send(file, offset, count)
  File "/root/.local/lib/python3.8/site-packages/gevent/_socket3.py", line 420, in _sendfile_use_send
    self._check_sendfile_params(file, offset, count)
  File "/root/.local/lib/python3.8/site-packages/gevent/_socket3.py", line 465, in _check_sendfile_params
    raise ValueError(
ValueError: count must be a positive integer (got 0)
```

Let us know if you need more information.

Thank you,
Loïc

**Comment by jkfran** [comment]
For the last traceback I found the following on StackOverflow:
https://stackoverflow.com/questions/68219233/run-flask-with-gunicorn-got-error-handling-request-count-must-be-a-positive-in

About the `SystemExit` we need to investigate.

**Comment by jkfran** [comment]
This issue has been fixed already. Thank you for opening it.
